[ req ]
default_bits           = 4096
default_md             = sha256
prompt                 = no
distinguished_name     = dn
x509_extensions        = v3_ca
utf8                   = yes

[ dn ]
countryName            = DE
stateOrProvinceName    = Hamburg
localityName           = Hamburg
organizationName       = Wjatscheslaw1986
commonName             = ca

[ v3_ca ]
subjectKeyIdentifier      = hash
authorityKeyIdentifier    = keyid:always,issuer
basicConstraints          = critical, CA:true, pathlen:0
keyUsage                  = critical, digitalSignature, keyEncipherment, cRLSign, keyCertSign
