[ req ]
default_bits        = 4096
default_md          = sha256
distinguished_name  = dn
req_extensions      = req_ext
utf8                = yes
prompt              = no

[ dn ]
C                   = DE
ST                  = Hamburg
L                   = Hamburg
O                   = Wjatscheslaw1986
CN                  = vsftp

[ req_ext ]
subjectAltName      = @alt_names

[ v3_server ]
basicConstraints    = critical,CA:false
keyUsage            = critical,digitalSignature,keyEncipherment
extendedKeyUsage    = serverAuth
subjectAltName      = @alt_names

[ alt_names ]
DNS.1               = ftp.wjatscheslaw1986.com
